console.log("Rodando o Sistema de Gerenciamento de Jogos")
console.log("Aplicação se conectando ao Banco de Dados")
console.log("Enviando arquivo para o GitHub")
console.log("Mais uma linha inserida para testar o commando Push dia 28-05-2022 as 10:19")
console.log("Enviando mais um teste para o GitHub")
console.log("vendo acontecer a atualizacao online no GitHub")